<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SltaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $sltas = [
            'MA LAIN-LAIN',
            'MA PERSIS 3 PAMEUNGPEUK',
            'MA PERSIS KATAPANG',
            'MA Sumur Bandung Cililin',
            'MAN 1 BOGOR',
            'MAN 1 KOTA BANDUNG',
            'MAN 2 KOTA BANDUNG',
            'MAN 2 PEKANBARU',
            'MAN 2 TANJUNG KARANG',
            'MAN I GARUT',
            'MAN SUBANG',
            'MAS HUSNUL KHOTIMAH',
            'MAS MULTI TEKNIK ASIH PUTERA CIMAHI',
            'MAS PERSIS',
            'SMA 1 CILEUNGSI',
            'SMA AL MUTTAQIN FULLDAY SCHOOL TASIKMALAYA',
            'SMA ALFA CENTAURI',
            'SMA ANGKASA 1',
            'SMA ANGKASA MARGAHAYU',
            'SMA HAYATAN THAYYIBAH',
            'SMA ISLAM CIPASUNG',
            'SMA LABORATORIUM UPI',
            'SMA LAIN-LAIN',
            'SMA MEDINA',
            'SMA MUHAMMADIYAH 4',
            'SMA NEGERI 1 TALANG UBI',
            'SMA NEGERI 11',
            'SMA NEGERI 2 LEMBANG',
            'SMA PASUNDAN 8',
            'SMA PLUS ASSALAAM DAYEUHKOLOT',
            'SMA PLUS MERDEKA SOREANG',
            'SMA SUMATERA 40 NO. 2',
            'SMAN 1 BALEENDAH',
            'SMAN 1 BANDUNG',
            'SMAN 1 BANJARAN',
            'SMAN 1 Batujajar',
            'SMAN 1 CIBADAK',
            'SMAN 1 CICALENGKA',
            'SMAN 1 CIKARANG UTARA',
            'SMAN 1 CILEUNYI',
            'SMAN 1 Cililin',
            'SMAN 1 CIPARAY',
            'SMAN 1 Cipatat',
            'SMAN 1 Cisarua',
            'SMAN 1 CIWIDEY',
            'SMAN 1 DEPOK',
            'SMAN 1 KATAPANG',
            'SMAN 1 KOTA SERANG',
            'SMAN 1 KUNINGAN',
            'SMAN 1 LELES / SMAN 2 GARUT',
            'SMAN 1 LEMAHABANG',
            'SMAN 1 MAJALAYA',
            'SMAN 1 MAJALENGKA',
            'SMAN 1 MARGAHAYU',
            'SMAN 1 Ngamprah',
            'SMAN 1 Padalarang',
            'SMAN 1 PALABUHAN RATU',
            'SMAN 1 PANGALENGAN',
            'SMAN 1 PLUMBON',
            'SMAN 1 RANCAEKEK',
            'SMAN 1 RANGKASBITUNG',
            'SMAN 1 SUBANG',
            'SMAN 1 TARAJU',
            'SMAN 1 TAROGONG KIDUL GARUT/SMAN 1 GARUT',
            'SMAN 10 BANDUNG',
            'SMAN 11 BANDUNG',
            'SMAN 113 JAKARTA',
            'SMAN 12 BANDUNG',
            'SMAN 13 BANDUNG',
            'SMAN 14 BANDUNG',
            'SMAN 17 BANDUNG',
            'SMAN 18 BANDUNG',
            'SMAN 18 Garut',
            'SMAN 19 BANDUNG',
            'SMAN 2 BANDUNG',
            'SMAN 2 CIMAHI',
            'SMAN 2 KS',
            'SMAN 2 KUDUS',
            'SMAN 2 TAROGONG KIDUL / SMAN 6 GARUT',
            'SMAN 2 TARUTUNG',
            'SMAN 21 BANDUNG',
            'SMAN 22 BANDUNG',
            'SMAN 23 BANDUNG',
            'SMAN 24 BANDUNG',
            'SMAN 3 BANDUNG',
            'SMAN 3 CIMAHI',
            'SMAN 3 KLATEN',
            'SMAN 3 TEGAL',
            'SMAN 4 BANDUNG',
            'SMAN 4 CIMAHI',
            'SMAN 5 BUKITTINGGI',
            'SMAN 5 CIMAHI',
            'SMAN 5 PAMEKASAN',
            'SMAN 6 BANDUNG',
            'SMAN 6 BEKASI',
            'SMAN 6 CIMAHI',
            'SMAN 7 BANDUNG',
            'SMAN 8 BANDUNG',
            'SMAN 9 Garut',
            'SMAN 9 KODYA BANDUNG',
            'SMEA Muh. Sragen',
            'SMK (STM) N 5 SEMARANG',
            'SMK ANGKASA',
            'SMK ICB CINTA NIAGA SMEA',
            'SMK LAIN-LAIN',
            'SMK Mahardika Batujajar',
            'SMK TARUNA BANGSA',
            'SMK TI PEMBANGUNAN CIMAHI',
            'SMKN 1 CIANJUR',
            'SMKN 1 CIMAHI',
            'SMKN 1 KATAPANG',
            'SMKN 1 KOTA BLITAR',
            'SMKN 1 PURWAKARTA',
            'SMKN 11 BANDUNG',
            'SMKN 13 BANDUNG',
            'SMKN 2 BANDUNG',
            'SMKN 4 BANDUNG',
            'SMKN 4 Padalarang',
            'SMKN PALASAH',
        ];

        foreach ($sltas as $nama_slta) {
            DB::table('slta')->insert([
                'nama_slta' => $nama_slta,
            ]);
        }
    }
}
