<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WilayahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Data lengkap 534 kabupaten/kota dari 38 provinsi di Indonesia
     * Koordinat berdasarkan ibukota masing-masing kabupaten/kota
     */
    public function run(): void
    {
        // Data lengkap wilayah (kabupaten/kota) dari seluruh Indonesia (534 total)
        $wilayahData = [
            // Provinsi Aceh (23 wilayah)
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Barat', 'latitude' => 4.1450, 'longitude' => 96.1289],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Barat Daya', 'latitude' => 3.7542, 'longitude' => 96.8225],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Besar', 'latitude' => 5.3083, 'longitude' => 95.6253],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Jaya', 'latitude' => 4.6333, 'longitude' => 95.5667],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Selatan', 'latitude' => 3.2667, 'longitude' => 97.1833],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Singkil', 'latitude' => 2.5000, 'longitude' => 97.7833],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Tamiang', 'latitude' => 4.3167, 'longitude' => 98.0500],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Tengah', 'latitude' => 4.6167, 'longitude' => 96.8500],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Tenggara', 'latitude' => 3.3667, 'longitude' => 97.8000],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Timur', 'latitude' => 4.9667, 'longitude' => 97.7667],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Aceh Utara', 'latitude' => 5.0333, 'longitude' => 97.2333],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Bener Meriah', 'latitude' => 4.7167, 'longitude' => 96.8500],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Bireuen', 'latitude' => 5.2000, 'longitude' => 96.7000],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Gayo Lues', 'latitude' => 3.9833, 'longitude' => 97.3500],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Nagan Raya', 'latitude' => 4.1333, 'longitude' => 96.5167],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Pidie', 'latitude' => 5.3833, 'longitude' => 95.9667],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Pidie Jaya', 'latitude' => 5.2289, 'longitude' => 96.2455],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kabupaten Simeulue', 'latitude' => 2.5833, 'longitude' => 96.3833],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kota Banda Aceh', 'latitude' => 5.5500, 'longitude' => 95.3167],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kota Langsa', 'latitude' => 4.4667, 'longitude' => 97.9667],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kota Lhokseumawe', 'latitude' => 5.1833, 'longitude' => 97.1500],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kota Sabang', 'latitude' => 5.8904, 'longitude' => 95.3160],
            ['provinsi' => 'Aceh', 'nama_wilayah' => 'Kota Subulussalam', 'latitude' => 2.7333, 'longitude' => 98.0000],

            // Provinsi Sumatera Utara (33 wilayah)
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Asahan', 'latitude' => 2.9833, 'longitude' => 99.6167],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Batu Bara', 'latitude' => 3.2000, 'longitude' => 99.3000],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Dairi', 'latitude' => 2.7500, 'longitude' => 98.3000],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Deli Serdang', 'latitude' => 3.5667, 'longitude' => 98.8667],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Humbang Hasundutan', 'latitude' => 2.2500, 'longitude' => 98.7000],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Karo', 'latitude' => 3.1000, 'longitude' => 98.5000],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Labuhanbatu', 'latitude' => 2.1000, 'longitude' => 100.0333],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Labuhanbatu Selatan', 'latitude' => 1.7667, 'longitude' => 100.1167],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Labuhanbatu Utara', 'latitude' => 2.5833, 'longitude' => 99.7500],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Langkat', 'latitude' => 3.7500, 'longitude' => 98.4500],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Mandailing Natal', 'latitude' => 1.0000, 'longitude' => 99.5667],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Nias', 'latitude' => 1.3000, 'longitude' => 97.6167],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Nias Barat', 'latitude' => 1.2500, 'longitude' => 97.2333],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Nias Selatan', 'latitude' => 0.5667, 'longitude' => 97.8167],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Nias Utara', 'latitude' => 1.4167, 'longitude' => 97.2500],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Padang Lawas', 'latitude' => 1.1667, 'longitude' => 99.8833],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Padang Lawas Utara', 'latitude' => 1.4667, 'longitude' => 99.6500],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Pakpak Bharat', 'latitude' => 2.6000, 'longitude' => 98.1167],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Samosir', 'latitude' => 2.6333, 'longitude' => 98.8167],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Serdang Bedagai', 'latitude' => 3.4833, 'longitude' => 99.0167],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Simalungun', 'latitude' => 2.8000, 'longitude' => 98.9500],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Tapanuli Selatan', 'latitude' => 1.6333, 'longitude' => 99.2833],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Tapanuli Tengah', 'latitude' => 1.6667, 'longitude' => 98.8333],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Tapanuli Utara', 'latitude' => 2.0167, 'longitude' => 98.9667],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kabupaten Toba', 'latitude' => 2.3333, 'longitude' => 99.0667],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kota Binjai', 'latitude' => 3.6000, 'longitude' => 98.4833],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kota Gunungsitoli', 'latitude' => 1.2833, 'longitude' => 97.6167],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kota Medan', 'latitude' => 3.5833, 'longitude' => 98.6667],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kota Padangsidimpuan', 'latitude' => 1.3667, 'longitude' => 99.2667],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kota Pematangsiantar', 'latitude' => 2.9667, 'longitude' => 99.0667],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kota Sibolga', 'latitude' => 1.7333, 'longitude' => 98.7833],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kota Tanjungbalai', 'latitude' => 2.9667, 'longitude' => 99.8000],
            ['provinsi' => 'Sumatera Utara', 'nama_wilayah' => 'Kota Tebing Tinggi', 'latitude' => 3.3333, 'longitude' => 99.1667],

            // Provinsi Sumatera Barat (19 wilayah)
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Agam', 'latitude' => -0.3167, 'longitude' => 100.0167],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Dharmasraya', 'latitude' => -1.0667, 'longitude' => 101.3667],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Kepulauan Mentawai', 'latitude' => -2.0667, 'longitude' => 99.5833],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Lima Puluh Kota', 'latitude' => -0.1167, 'longitude' => 100.5167],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Padang Pariaman', 'latitude' => -0.6611, 'longitude' => 100.1906],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Pasaman', 'latitude' => 0.1333, 'longitude' => 100.1667],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Pasaman Barat', 'latitude' => 0.1167, 'longitude' => 99.9167],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Pesisir Selatan', 'latitude' => -1.3500, 'longitude' => 100.5667],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Sijunjung', 'latitude' => -0.6833, 'longitude' => 100.9667],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Solok', 'latitude' => -0.9167, 'longitude' => 100.5667],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Solok Selatan', 'latitude' => -1.2833, 'longitude' => 101.1000],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kabupaten Tanah Datar', 'latitude' => -0.4500, 'longitude' => 100.5833],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kota Bukittinggi', 'latitude' => -0.3000, 'longitude' => 100.3667],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kota Padang', 'latitude' => -0.9500, 'longitude' => 100.3500],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kota Padang Panjang', 'latitude' => -0.4667, 'longitude' => 100.4167],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kota Pariaman', 'latitude' => -0.6167, 'longitude' => 100.1167],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kota Payakumbuh', 'latitude' => -0.2167, 'longitude' => 100.6333],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kota Sawahlunto', 'latitude' => -0.6833, 'longitude' => 100.7833],
            ['provinsi' => 'Sumatera Barat', 'nama_wilayah' => 'Kota Solok', 'latitude' => -0.7833, 'longitude' => 100.6667],

            // Provinsi Riau (12 wilayah)
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Bengkalis', 'latitude' => 1.4667, 'longitude' => 102.1000],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Indragiri Hilir', 'latitude' => -0.3333, 'longitude' => 103.1500],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Indragiri Hulu', 'latitude' => -0.3667, 'longitude' => 102.5333],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Kampar', 'latitude' => 0.3333, 'longitude' => 101.0333],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Kepulauan Meranti', 'latitude' => 0.9833, 'longitude' => 102.7000],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Kuantan Singingi', 'latitude' => -0.5167, 'longitude' => 101.5333],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Pelalawan', 'latitude' => 0.3833, 'longitude' => 101.8500],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Rokan Hilir', 'latitude' => 2.1500, 'longitude' => 100.8167],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Rokan Hulu', 'latitude' => 0.8500, 'longitude' => 100.3167],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kabupaten Siak', 'latitude' => 0.8000, 'longitude' => 102.0333],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kota Dumai', 'latitude' => 1.6667, 'longitude' => 101.4500],
            ['provinsi' => 'Riau', 'nama_wilayah' => 'Kota Pekanbaru', 'latitude' => 0.5333, 'longitude' => 101.4500],

            // Provinsi Jambi (11 wilayah)
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Batanghari', 'latitude' => -1.7167, 'longitude' => 103.2667],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Bungo', 'latitude' => -1.5167, 'longitude' => 102.1000],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Kerinci', 'latitude' => -2.0833, 'longitude' => 101.4667],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Merangin', 'latitude' => -2.0667, 'longitude' => 102.2833],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Muaro Jambi', 'latitude' => -1.5667, 'longitude' => 103.5833],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Sarolangun', 'latitude' => -2.3167, 'longitude' => 102.7333],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Tanjung Jabung Barat', 'latitude' => -0.8167, 'longitude' => 103.4667],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Tanjung Jabung Timur', 'latitude' => -1.1333, 'longitude' => 103.8667],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kabupaten Tebo', 'latitude' => -1.4833, 'longitude' => 102.4333],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kota Jambi', 'latitude' => -1.6000, 'longitude' => 103.6167],
            ['provinsi' => 'Jambi', 'nama_wilayah' => 'Kota Sungai Penuh', 'latitude' => -2.0667, 'longitude' => 101.3833],

            // Provinsi Sumatera Selatan (17 wilayah)
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Banyuasin', 'latitude' => -2.8833, 'longitude' => 104.3833],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Empat Lawang', 'latitude' => -3.6117, 'longitude' => 103.0689],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Lahat', 'latitude' => -3.7833, 'longitude' => 103.5333],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Muara Enim', 'latitude' => -3.6500, 'longitude' => 103.6167],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Musi Banyuasin', 'latitude' => -2.8833, 'longitude' => 104.0833],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Musi Rawas', 'latitude' => -3.2500, 'longitude' => 102.9333],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Musi Rawas Utara', 'latitude' => -2.5333, 'longitude' => 102.7833],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Ogan Ilir', 'latitude' => -3.2167, 'longitude' => 104.6500],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Ogan Komering Ilir', 'latitude' => -3.3667, 'longitude' => 104.8500],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Ogan Komering Ulu', 'latitude' => -4.1333, 'longitude' => 104.1667],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Ogan Komering Ulu Selatan', 'latitude' => -4.5833, 'longitude' => 103.8833],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Ogan Komering Ulu Timur', 'latitude' => -4.3500, 'longitude' => 104.3500],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kabupaten Penukal Abab Lematang Ilir', 'latitude' => -3.2833, 'longitude' => 103.8333],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kota Lubuklinggau', 'latitude' => -3.1500, 'longitude' => 102.8667],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kota Pagar Alam', 'latitude' => -4.0000, 'longitude' => 103.2500],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kota Palembang', 'latitude' => -2.9833, 'longitude' => 104.7500],
            ['provinsi' => 'Sumatera Selatan', 'nama_wilayah' => 'Kota Prabumulih', 'latitude' => -3.4333, 'longitude' => 104.2333],

            // Provinsi Bengkulu (10 wilayah)
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Bengkulu Selatan', 'latitude' => -4.4000, 'longitude' => 102.9167],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Bengkulu Tengah', 'latitude' => -3.7833, 'longitude' => 102.4500],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Bengkulu Utara', 'latitude' => -3.7167, 'longitude' => 102.3167],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Kaur', 'latitude' => -4.7938, 'longitude' => 103.3494],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Kepahiang', 'latitude' => -3.6130, 'longitude' => 102.6676],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Lebong', 'latitude' => -3.2428, 'longitude' => 102.3349],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Mukomuko', 'latitude' => -2.5529, 'longitude' => 101.1042],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Rejang Lebong', 'latitude' => -3.4667, 'longitude' => 102.5167],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kabupaten Seluma', 'latitude' => -3.9667, 'longitude' => 102.4833],
            ['provinsi' => 'Bengkulu', 'nama_wilayah' => 'Kota Bengkulu', 'latitude' => -3.7833, 'longitude' => 102.2667],

            // Provinsi Lampung (15 wilayah)
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Lampung Barat', 'latitude' => -5.0500, 'longitude' => 104.0833],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Lampung Selatan', 'latitude' => -5.7500, 'longitude' => 105.6000],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Lampung Tengah', 'latitude' => -5.1167, 'longitude' => 105.2500],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Lampung Timur', 'latitude' => -5.0667, 'longitude' => 105.5167],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Lampung Utara', 'latitude' => -4.8300, 'longitude' => 104.8700],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Mesuji', 'latitude' => -3.8833, 'longitude' => 105.7167],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Pesawaran', 'latitude' => -5.4500, 'longitude' => 105.0833],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Pesisir Barat', 'latitude' => -5.1833, 'longitude' => 103.9333],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Pringsewu', 'latitude' => -5.3500, 'longitude' => 104.9667],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Tanggamus', 'latitude' => -5.5167, 'longitude' => 104.6333],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Tulang Bawang', 'latitude' => -4.4500, 'longitude' => 105.2667],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Tulang Bawang Barat', 'latitude' => -4.3500, 'longitude' => 105.0833],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kabupaten Way Kanan', 'latitude' => -4.5667, 'longitude' => 104.5333],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kota Bandar Lampung', 'latitude' => -5.4167, 'longitude' => 105.2500],
            ['provinsi' => 'Lampung', 'nama_wilayah' => 'Kota Metro', 'latitude' => -5.1167, 'longitude' => 105.3000],

            // Provinsi Kepulauan Bangka Belitung (7 wilayah)
            ['provinsi' => 'Kepulauan Bangka Belitung', 'nama_wilayah' => 'Kabupaten Bangka', 'latitude' => -1.8787, 'longitude' => 106.1159],
            ['provinsi' => 'Kepulauan Bangka Belitung', 'nama_wilayah' => 'Kabupaten Bangka Barat', 'latitude' => -2.0648, 'longitude' => 105.1647],
            ['provinsi' => 'Kepulauan Bangka Belitung', 'nama_wilayah' => 'Kabupaten Bangka Selatan', 'latitude' => -3.0000, 'longitude' => 106.4667],
            ['provinsi' => 'Kepulauan Bangka Belitung', 'nama_wilayah' => 'Kabupaten Bangka Tengah', 'latitude' => -2.4990, 'longitude' => 106.4041],
            ['provinsi' => 'Kepulauan Bangka Belitung', 'nama_wilayah' => 'Kabupaten Belitung', 'latitude' => -2.7380, 'longitude' => 107.6377],
            ['provinsi' => 'Kepulauan Bangka Belitung', 'nama_wilayah' => 'Kabupaten Belitung Timur', 'latitude' => -2.8657, 'longitude' => 108.2775],
            ['provinsi' => 'Kepulauan Bangka Belitung', 'nama_wilayah' => 'Kota Pangkal Pinang', 'latitude' => -2.1333, 'longitude' => 106.1333],

            // Provinsi Kepulauan Riau (7 wilayah)
            ['provinsi' => 'Kepulauan Riau', 'nama_wilayah' => 'Kabupaten Bintan', 'latitude' => 1.0500, 'longitude' => 104.5167],
            ['provinsi' => 'Kepulauan Riau', 'nama_wilayah' => 'Kabupaten Karimun', 'latitude' => 1.0000, 'longitude' => 103.4217],
            ['provinsi' => 'Kepulauan Riau', 'nama_wilayah' => 'Kabupaten Kepulauan Anambas', 'latitude' => 3.2166, 'longitude' => 106.2181],
            ['provinsi' => 'Kepulauan Riau', 'nama_wilayah' => 'Kabupaten Lingga', 'latitude' => -0.1667, 'longitude' => 104.6500],
            ['provinsi' => 'Kepulauan Riau', 'nama_wilayah' => 'Kabupaten Natuna', 'latitude' => 3.9167, 'longitude' => 108.3833],
            ['provinsi' => 'Kepulauan Riau', 'nama_wilayah' => 'Kota Batam', 'latitude' => 1.0500, 'longitude' => 104.0000],
            ['provinsi' => 'Kepulauan Riau', 'nama_wilayah' => 'Kota Tanjung Pinang', 'latitude' => 0.9333, 'longitude' => 104.4500],

            // Provinsi DKI Jakarta (6 wilayah)
            ['provinsi' => 'DKI Jakarta', 'nama_wilayah' => 'Kabupaten Adm. Kepulauan Seribu', 'latitude' => -5.7436, 'longitude' => 106.6111],
            ['provinsi' => 'DKI Jakarta', 'nama_wilayah' => 'Kota Adm. Jakarta Barat', 'latitude' => -6.1833, 'longitude' => 106.7500],
            ['provinsi' => 'DKI Jakarta', 'nama_wilayah' => 'Kota Adm. Jakarta Pusat', 'latitude' => -6.1870, 'longitude' => 106.8370],
            ['provinsi' => 'DKI Jakarta', 'nama_wilayah' => 'Kota Adm. Jakarta Selatan', 'latitude' => -6.2500, 'longitude' => 106.8000],
            ['provinsi' => 'DKI Jakarta', 'nama_wilayah' => 'Kota Adm. Jakarta Timur', 'latitude' => -6.1950, 'longitude' => 106.9400],
            ['provinsi' => 'DKI Jakarta', 'nama_wilayah' => 'Kota Adm. Jakarta Utara', 'latitude' => -6.1167, 'longitude' => 106.9000],

            // Provinsi Jawa Barat (27 wilayah)
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Bandung', 'latitude' => -7.0208, 'longitude' => 107.5192],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Bandung Barat', 'latitude' => -6.8419, 'longitude' => 107.4897],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Bekasi', 'latitude' => -6.2917, 'longitude' => 107.1500],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Bogor', 'latitude' => -6.4833, 'longitude' => 106.8333],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Ciamis', 'latitude' => -7.3333, 'longitude' => 108.3500],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Cianjur', 'latitude' => -6.8167, 'longitude' => 107.1333],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Cirebon', 'latitude' => -6.7500, 'longitude' => 108.4833],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Garut', 'latitude' => -7.2167, 'longitude' => 107.9000],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Indramayu', 'latitude' => -6.3333, 'longitude' => 108.3333],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Karawang', 'latitude' => -6.3000, 'longitude' => 107.3000],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Kuningan', 'latitude' => -6.9833, 'longitude' => 108.4833],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Majalengka', 'latitude' => -6.8333, 'longitude' => 108.2333],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Pangandaran', 'latitude' => -7.6833, 'longitude' => 108.5000],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Purwakarta', 'latitude' => -6.5500, 'longitude' => 107.4500],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Subang', 'latitude' => -6.5667, 'longitude' => 107.7667],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Sukabumi', 'latitude' => -6.9833, 'longitude' => 106.5500],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Sumedang', 'latitude' => -6.8500, 'longitude' => 107.9167],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kabupaten Tasikmalaya', 'latitude' => -7.3500, 'longitude' => 108.1167],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Bandung', 'latitude' => -6.9167, 'longitude' => 107.6167],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Banjar', 'latitude' => -7.3667, 'longitude' => 108.5333],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Bekasi', 'latitude' => -6.2333, 'longitude' => 106.9833],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Bogor', 'latitude' => -6.5833, 'longitude' => 106.8000],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Cimahi', 'latitude' => -6.8833, 'longitude' => 107.5333],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Cirebon', 'latitude' => -6.7167, 'longitude' => 108.5667],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Depok', 'latitude' => -6.4000, 'longitude' => 106.8167],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Sukabumi', 'latitude' => -6.9167, 'longitude' => 106.9167],
            ['provinsi' => 'Jawa Barat', 'nama_wilayah' => 'Kota Tasikmalaya', 'latitude' => -7.3333, 'longitude' => 108.2167],

            // Provinsi Jawa Tengah (35 wilayah)
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Banjarnegara', 'latitude' => -7.4000, 'longitude' => 109.7000],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Banyumas', 'latitude' => -7.4167, 'longitude' => 109.2333],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Batang', 'latitude' => -6.9000, 'longitude' => 109.7333],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Blora', 'latitude' => -6.9667, 'longitude' => 111.4167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Boyolali', 'latitude' => -7.5333, 'longitude' => 110.6000],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Brebes', 'latitude' => -6.8667, 'longitude' => 109.0500],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Cilacap', 'latitude' => -7.7333, 'longitude' => 109.0167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Demak', 'latitude' => -6.9000, 'longitude' => 110.6333],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Grobogan', 'latitude' => -7.0833, 'longitude' => 110.9167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Jepara', 'latitude' => -6.5833, 'longitude' => 110.6667],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Karanganyar', 'latitude' => -7.6000, 'longitude' => 110.9500],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Kebumen', 'latitude' => -7.6667, 'longitude' => 109.6667],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Kendal', 'latitude' => -6.9333, 'longitude' => 110.2000],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Klaten', 'latitude' => -7.7000, 'longitude' => 110.6000],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Kudus', 'latitude' => -6.8000, 'longitude' => 110.8333],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Magelang', 'latitude' => -7.6000, 'longitude' => 110.2167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Pati', 'latitude' => -6.7500, 'longitude' => 111.0333],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Pekalongan', 'latitude' => -7.0333, 'longitude' => 109.6000],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Pemalang', 'latitude' => -6.9000, 'longitude' => 109.3833],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Purbalingga', 'latitude' => -7.3833, 'longitude' => 109.3667],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Purworejo', 'latitude' => -7.7167, 'longitude' => 109.9167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Rembang', 'latitude' => -6.7000, 'longitude' => 111.3333],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Semarang', 'latitude' => -7.1333, 'longitude' => 110.4000],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Sragen', 'latitude' => -7.4167, 'longitude' => 111.0167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Sukoharjo', 'latitude' => -7.6833, 'longitude' => 110.8333],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Tegal', 'latitude' => -6.9833, 'longitude' => 109.1333],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Temanggung', 'latitude' => -7.3167, 'longitude' => 110.1833],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Wonogiri', 'latitude' => -7.8167, 'longitude' => 110.9167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kabupaten Wonosobo', 'latitude' => -7.3667, 'longitude' => 109.9000],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kota Magelang', 'latitude' => -7.4667, 'longitude' => 110.2167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kota Pekalongan', 'latitude' => -6.8833, 'longitude' => 109.6667],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kota Salatiga', 'latitude' => -7.3333, 'longitude' => 110.5000],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kota Semarang', 'latitude' => -6.9667, 'longitude' => 110.4167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kota Surakarta', 'latitude' => -7.5667, 'longitude' => 110.8167],
            ['provinsi' => 'Jawa Tengah', 'nama_wilayah' => 'Kota Tegal', 'latitude' => -6.8667, 'longitude' => 109.1333],

            // Provinsi DI Yogyakarta (5 wilayah)
            ['provinsi' => 'DI Yogyakarta', 'nama_wilayah' => 'Kabupaten Bantul', 'latitude' => -7.9167, 'longitude' => 110.3333],
            ['provinsi' => 'DI Yogyakarta', 'nama_wilayah' => 'Kabupaten Gunungkidul', 'latitude' => -7.9667, 'longitude' => 110.6000],
            ['provinsi' => 'DI Yogyakarta', 'nama_wilayah' => 'Kabupaten Kulon Progo', 'latitude' => -7.8667, 'longitude' => 110.1500],
            ['provinsi' => 'DI Yogyakarta', 'nama_wilayah' => 'Kabupaten Sleman', 'latitude' => -7.7000, 'longitude' => 110.3667],
            ['provinsi' => 'DI Yogyakarta', 'nama_wilayah' => 'Kota Yogyakarta', 'latitude' => -7.8000, 'longitude' => 110.3667],

            // Provinsi Jawa Timur (38 wilayah)
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Bangkalan', 'latitude' => -7.0500, 'longitude' => 112.7333],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Banyuwangi', 'latitude' => -8.2167, 'longitude' => 114.3667],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Blitar', 'latitude' => -8.1000, 'longitude' => 112.1667],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Bojonegoro', 'latitude' => -7.1500, 'longitude' => 111.8833],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Bondowoso', 'latitude' => -7.9167, 'longitude' => 113.8167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Gresik', 'latitude' => -7.1667, 'longitude' => 112.6500],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Jember', 'latitude' => -8.1667, 'longitude' => 113.7000],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Jombang', 'latitude' => -7.5500, 'longitude' => 112.2333],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Kediri', 'latitude' => -7.7667, 'longitude' => 112.1667],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Lamongan', 'latitude' => -7.1167, 'longitude' => 112.4167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Lumajang', 'latitude' => -8.1333, 'longitude' => 113.2167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Madiun', 'latitude' => -7.5167, 'longitude' => 111.6333],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Magetan', 'latitude' => -7.6500, 'longitude' => 111.3333],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Malang', 'latitude' => -8.1333, 'longitude' => 112.5667],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Mojokerto', 'latitude' => -7.5167, 'longitude' => 112.5333],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Nganjuk', 'latitude' => -7.6000, 'longitude' => 111.9000],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Ngawi', 'latitude' => -7.4000, 'longitude' => 111.4500],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Pacitan', 'latitude' => -8.2000, 'longitude' => 111.1000],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Pamekasan', 'latitude' => -7.1667, 'longitude' => 113.4667],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Pasuruan', 'latitude' => -7.6000, 'longitude' => 112.7833],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Ponorogo', 'latitude' => -7.8667, 'longitude' => 111.4667],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Probolinggo', 'latitude' => -7.7500, 'longitude' => 113.4167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Sampang', 'latitude' => -7.1833, 'longitude' => 113.2333],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Sidoarjo', 'latitude' => -7.4500, 'longitude' => 112.7167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Situbondo', 'latitude' => -7.7000, 'longitude' => 114.0167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Sumenep', 'latitude' => -7.0167, 'longitude' => 113.8667],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Trenggalek', 'latitude' => -8.0500, 'longitude' => 111.7167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Tuban', 'latitude' => -6.9000, 'longitude' => 112.0500],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kabupaten Tulungagung', 'latitude' => -8.0667, 'longitude' => 111.9000],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Batu', 'latitude' => -7.8833, 'longitude' => 112.5167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Blitar', 'latitude' => -8.1000, 'longitude' => 112.1667],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Kediri', 'latitude' => -7.8167, 'longitude' => 112.0167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Madiun', 'latitude' => -7.6333, 'longitude' => 111.5333],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Malang', 'latitude' => -7.9833, 'longitude' => 112.6167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Mojokerto', 'latitude' => -7.4667, 'longitude' => 112.4333],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Pasuruan', 'latitude' => -7.6500, 'longitude' => 112.9000],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Probolinggo', 'latitude' => -7.7500, 'longitude' => 113.2167],
            ['provinsi' => 'Jawa Timur', 'nama_wilayah' => 'Kota Surabaya', 'latitude' => -7.2500, 'longitude' => 112.7500],

            // Provinsi Banten (8 wilayah)
            ['provinsi' => 'Banten', 'nama_wilayah' => 'Kabupaten Lebak', 'latitude' => -6.3667, 'longitude' => 106.2500],
            ['provinsi' => 'Banten', 'nama_wilayah' => 'Kabupaten Pandeglang', 'latitude' => -6.3167, 'longitude' => 106.1000],
            ['provinsi' => 'Banten', 'nama_wilayah' => 'Kabupaten Serang', 'latitude' => -6.1167, 'longitude' => 106.3000],
            ['provinsi' => 'Banten', 'nama_wilayah' => 'Kabupaten Tangerang', 'latitude' => -6.2333, 'longitude' => 106.5167],
            ['provinsi' => 'Banten', 'nama_wilayah' => 'Kota Cilegon', 'latitude' => -6.0167, 'longitude' => 106.0500],
            ['provinsi' => 'Banten', 'nama_wilayah' => 'Kota Serang', 'latitude' => -6.1167, 'longitude' => 106.1500],
            ['provinsi' => 'Banten', 'nama_wilayah' => 'Kota Tangerang', 'latitude' => -6.1833, 'longitude' => 106.6333],
            ['provinsi' => 'Banten', 'nama_wilayah' => 'Kota Tangerang Selatan', 'latitude' => -6.2833, 'longitude' => 106.7167],

            // Provinsi Bali (9 wilayah)
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kabupaten Badung', 'latitude' => -8.6500, 'longitude' => 115.1667],
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kabupaten Bangli', 'latitude' => -8.4500, 'longitude' => 115.3500],
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kabupaten Buleleng', 'latitude' => -8.1167, 'longitude' => 115.0833],
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kabupaten Gianyar', 'latitude' => -8.5333, 'longitude' => 115.3167],
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kabupaten Jembrana', 'latitude' => -8.3500, 'longitude' => 114.6167],
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kabupaten Karangasem', 'latitude' => -8.4500, 'longitude' => 115.6167],
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kabupaten Klungkung', 'latitude' => -8.5333, 'longitude' => 115.4000],
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kabupaten Tabanan', 'latitude' => -8.5333, 'longitude' => 115.1167],
            ['provinsi' => 'Bali', 'nama_wilayah' => 'Kota Denpasar', 'latitude' => -8.6500, 'longitude' => 115.2167],

            // Provinsi Nusa Tenggara Barat (10 wilayah)
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kabupaten Bima', 'latitude' => -8.5000, 'longitude' => 118.7000],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kabupaten Dompu', 'latitude' => -8.5333, 'longitude' => 118.4667],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kabupaten Lombok Barat', 'latitude' => -8.6500, 'longitude' => 116.0833],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kabupaten Lombok Tengah', 'latitude' => -8.7167, 'longitude' => 116.2667],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kabupaten Lombok Timur', 'latitude' => -8.6500, 'longitude' => 116.5333],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kabupaten Lombok Utara', 'latitude' => -8.3500, 'longitude' => 116.1333],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kabupaten Sumbawa', 'latitude' => -8.5000, 'longitude' => 117.4167],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kabupaten Sumbawa Barat', 'latitude' => -8.7500, 'longitude' => 116.8500],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kota Bima', 'latitude' => -8.4667, 'longitude' => 118.7167],
            ['provinsi' => 'Nusa Tenggara Barat', 'nama_wilayah' => 'Kota Mataram', 'latitude' => -8.5833, 'longitude' => 116.1167],

            // Provinsi Nusa Tenggara Timur (22 wilayah)
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Alor', 'latitude' => -8.2167, 'longitude' => 124.5167],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Belu', 'latitude' => -9.1000, 'longitude' => 124.9000],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Ende', 'latitude' => -8.8500, 'longitude' => 121.6500],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Flores Timur', 'latitude' => -8.3333, 'longitude' => 122.9833],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Kupang', 'latitude' => -10.1667, 'longitude' => 123.7500],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Lembata', 'latitude' => -8.3667, 'longitude' => 123.5000],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Malaka', 'latitude' => -9.5833, 'longitude' => 124.9167],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Manggarai', 'latitude' => -8.6167, 'longitude' => 120.4667],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Manggarai Barat', 'latitude' => -8.5000, 'longitude' => 119.8833],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Manggarai Timur', 'latitude' => -8.6667, 'longitude' => 120.6333],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Nagekeo', 'latitude' => -8.5333, 'longitude' => 121.2167],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Ngada', 'latitude' => -8.7833, 'longitude' => 120.9667],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Rote Ndao', 'latitude' => -10.4833, 'longitude' => 123.0500],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Sabu Raijua', 'latitude' => -10.5000, 'longitude' => 121.8333],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Sikka', 'latitude' => -8.6167, 'longitude' => 122.2167],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Sumba Barat', 'latitude' => -9.6500, 'longitude' => 119.3833],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Sumba Barat Daya', 'latitude' => -9.4167, 'longitude' => 119.0667],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Sumba Tengah', 'latitude' => -9.6500, 'longitude' => 119.6000],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Sumba Timur', 'latitude' => -9.6500, 'longitude' => 120.2667],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Timor Tengah Selatan', 'latitude' => -9.8667, 'longitude' => 124.2833],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kabupaten Timor Tengah Utara', 'latitude' => -9.4500, 'longitude' => 124.4833],
            ['provinsi' => 'Nusa Tenggara Timur', 'nama_wilayah' => 'Kota Kupang', 'latitude' => -10.1667, 'longitude' => 123.5833],

            // Provinsi Kalimantan Barat (14 wilayah)
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Bengkayang', 'latitude' => 0.8333, 'longitude' => 109.9667],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Kapuas Hulu', 'latitude' => 0.8500, 'longitude' => 112.9333],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Kayong Utara', 'latitude' => -1.2500, 'longitude' => 109.9500],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Ketapang', 'latitude' => -1.8500, 'longitude' => 109.9667],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Kubu Raya', 'latitude' => -0.0500, 'longitude' => 109.3333],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Landak', 'latitude' => 0.3500, 'longitude' => 109.4500],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Melawi', 'latitude' => -0.8000, 'longitude' => 111.7500],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Mempawah', 'latitude' => 0.4500, 'longitude' => 109.0000],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Sambas', 'latitude' => 1.3500, 'longitude' => 109.3000],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Sanggau', 'latitude' => 0.1167, 'longitude' => 110.5833],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Sekadau', 'latitude' => -0.0167, 'longitude' => 110.9500],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kabupaten Sintang', 'latitude' => 0.0833, 'longitude' => 111.4833],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kota Pontianak', 'latitude' => -0.0167, 'longitude' => 109.3333],
            ['provinsi' => 'Kalimantan Barat', 'nama_wilayah' => 'Kota Singkawang', 'latitude' => 0.9000, 'longitude' => 109.0000],

            // Provinsi Kalimantan Tengah (14 wilayah)
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Barito Selatan', 'latitude' => -1.6833, 'longitude' => 114.9000],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Barito Timur', 'latitude' => -1.9167, 'longitude' => 115.1167],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Barito Utara', 'latitude' => -0.9500, 'longitude' => 114.9000],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Gunung Mas', 'latitude' => -0.9833, 'longitude' => 113.8833],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Kapuas', 'latitude' => -3.0000, 'longitude' => 114.3833],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Katingan', 'latitude' => -2.0667, 'longitude' => 113.4000],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Kotawaringin Barat', 'latitude' => -2.6833, 'longitude' => 111.6167],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Kotawaringin Timur', 'latitude' => -2.5333, 'longitude' => 112.9500],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Lamandau', 'latitude' => -2.1833, 'longitude' => 111.4500],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Murung Raya', 'latitude' => -0.5833, 'longitude' => 114.5667],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Pulang Pisau', 'latitude' => -2.7667, 'longitude' => 114.2500],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Seruyan', 'latitude' => -3.3667, 'longitude' => 112.5167],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kabupaten Sukamara', 'latitude' => -2.9833, 'longitude' => 111.2333],
            ['provinsi' => 'Kalimantan Tengah', 'nama_wilayah' => 'Kota Palangka Raya', 'latitude' => -2.2167, 'longitude' => 113.9167],

            // Provinsi Kalimantan Selatan (13 wilayah)
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Balangan', 'latitude' => -2.3333, 'longitude' => 115.4667],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Banjar', 'latitude' => -3.4167, 'longitude' => 114.8333],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Barito Kuala', 'latitude' => -3.0000, 'longitude' => 114.7667],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Hulu Sungai Selatan', 'latitude' => -2.7667, 'longitude' => 115.1667],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Hulu Sungai Tengah', 'latitude' => -2.5833, 'longitude' => 115.3833],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Hulu Sungai Utara', 'latitude' => -2.4167, 'longitude' => 115.2500],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Kotabaru', 'latitude' => -3.2333, 'longitude' => 116.2167],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Tabalong', 'latitude' => -2.1667, 'longitude' => 115.4000],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Tanah Bumbu', 'latitude' => -3.4333, 'longitude' => 115.9667],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Tanah Laut', 'latitude' => -3.8000, 'longitude' => 114.7667],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kabupaten Tapin', 'latitude' => -2.9333, 'longitude' => 115.1000],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kota Banjarbaru', 'latitude' => -3.4333, 'longitude' => 114.8167],
            ['provinsi' => 'Kalimantan Selatan', 'nama_wilayah' => 'Kota Banjarmasin', 'latitude' => -3.3167, 'longitude' => 114.5833],

            // Provinsi Kalimantan Timur (10 wilayah)
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kabupaten Berau', 'latitude' => 2.1500, 'longitude' => 117.5000],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kabupaten Kutai Barat', 'latitude' => -0.2500, 'longitude' => 115.6500],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kabupaten Kutai Kartanegara', 'latitude' => -0.4333, 'longitude' => 116.9833],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kabupaten Kutai Timur', 'latitude' => 0.5167, 'longitude' => 117.5667],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kabupaten Mahakam Ulu', 'latitude' => 0.4667, 'longitude' => 114.9333],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kabupaten Paser', 'latitude' => -1.6167, 'longitude' => 116.2167],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kabupaten Penajam Paser Utara', 'latitude' => -1.2500, 'longitude' => 116.7167],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kota Balikpapan', 'latitude' => -1.2667, 'longitude' => 116.8333],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kota Bontang', 'latitude' => 0.1333, 'longitude' => 117.5000],
            ['provinsi' => 'Kalimantan Timur', 'nama_wilayah' => 'Kota Samarinda', 'latitude' => -0.5000, 'longitude' => 117.1500],

            // Provinsi Kalimantan Utara (5 wilayah)
            ['provinsi' => 'Kalimantan Utara', 'nama_wilayah' => 'Kabupaten Bulungan', 'latitude' => 2.8333, 'longitude' => 117.3667],
            ['provinsi' => 'Kalimantan Utara', 'nama_wilayah' => 'Kabupaten Malinau', 'latitude' => 3.5833, 'longitude' => 116.6333],
            ['provinsi' => 'Kalimantan Utara', 'nama_wilayah' => 'Kabupaten Nunukan', 'latitude' => 4.0500, 'longitude' => 117.6667],
            ['provinsi' => 'Kalimantan Utara', 'nama_wilayah' => 'Kabupaten Tana Tidung', 'latitude' => 3.4833, 'longitude' => 117.1667],
            ['provinsi' => 'Kalimantan Utara', 'nama_wilayah' => 'Kota Tarakan', 'latitude' => 3.3000, 'longitude' => 117.6333],

            // Provinsi Sulawesi Utara (15 wilayah)
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Bolaang Mongondow', 'latitude' => 0.9167, 'longitude' => 124.0333],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Bolaang Mongondow Selatan', 'latitude' => 0.3667, 'longitude' => 123.9000],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Bolaang Mongondow Timur', 'latitude' => 0.7667, 'longitude' => 124.6333],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Bolaang Mongondow Utara', 'latitude' => 1.0000, 'longitude' => 123.4000],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Kepulauan Sangihe', 'latitude' => 3.6000, 'longitude' => 125.5000],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Kepulauan Siau Tagulandang Biaro', 'latitude' => 2.7000, 'longitude' => 125.4000],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Kepulauan Talaud', 'latitude' => 4.0167, 'longitude' => 126.7000],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Minahasa', 'latitude' => 1.3000, 'longitude' => 124.9167],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Minahasa Selatan', 'latitude' => 1.1833, 'longitude' => 124.5667],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Minahasa Tenggara', 'latitude' => 1.0500, 'longitude' => 124.8167],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kabupaten Minahasa Utara', 'latitude' => 1.3833, 'longitude' => 124.9833],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kota Bitung', 'latitude' => 1.4333, 'longitude' => 125.1833],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kota Kotamobagu', 'latitude' => 0.7333, 'longitude' => 124.3167],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kota Manado', 'latitude' => 1.4833, 'longitude' => 124.8500],
            ['provinsi' => 'Sulawesi Utara', 'nama_wilayah' => 'Kota Tomohon', 'latitude' => 1.3167, 'longitude' => 124.8333],

            // Provinsi Sulawesi Tengah (13 wilayah)
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Banggai', 'latitude' => -0.9500, 'longitude' => 122.9000],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Banggai Kepulauan', 'latitude' => -1.2167, 'longitude' => 123.3667],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Banggai Laut', 'latitude' => -1.5833, 'longitude' => 123.5333],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Buol', 'latitude' => 1.1167, 'longitude' => 121.4167],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Donggala', 'latitude' => -0.6667, 'longitude' => 119.7333],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Morowali', 'latitude' => -2.5500, 'longitude' => 121.9333],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Morowali Utara', 'latitude' => -2.0000, 'longitude' => 121.3167],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Parigi Moutong', 'latitude' => -0.9000, 'longitude' => 120.2000],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Poso', 'latitude' => -1.4000, 'longitude' => 120.7500],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Sigi', 'latitude' => -0.9500, 'longitude' => 119.9833],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Tojo Una-Una', 'latitude' => -0.8500, 'longitude' => 121.6000],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kabupaten Tolitoli', 'latitude' => 1.0333, 'longitude' => 120.8167],
            ['provinsi' => 'Sulawesi Tengah', 'nama_wilayah' => 'Kota Palu', 'latitude' => -0.9000, 'longitude' => 119.8500],

            // Provinsi Sulawesi Selatan (24 wilayah)
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Bantaeng', 'latitude' => -5.5500, 'longitude' => 120.0000],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Barru', 'latitude' => -4.4333, 'longitude' => 119.6167],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Bone', 'latitude' => -4.5333, 'longitude' => 120.3167],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Bulukumba', 'latitude' => -5.3333, 'longitude' => 120.2000],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Enrekang', 'latitude' => -3.5667, 'longitude' => 119.7833],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Gowa', 'latitude' => -5.1667, 'longitude' => 119.4667],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Jeneponto', 'latitude' => -5.6667, 'longitude' => 119.7167],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Kepulauan Selayar', 'latitude' => -6.1000, 'longitude' => 120.4500],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Luwu', 'latitude' => -3.3833, 'longitude' => 120.1833],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Luwu Timur', 'latitude' => -2.6500, 'longitude' => 121.1000],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Luwu Utara', 'latitude' => -2.5667, 'longitude' => 120.3000],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Maros', 'latitude' => -5.0000, 'longitude' => 119.5667],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Pangkajene dan Kepulauan', 'latitude' => -4.8333, 'longitude' => 119.5333],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Pinrang', 'latitude' => -3.9000, 'longitude' => 119.6500],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Sidenreng Rappang', 'latitude' => -3.9167, 'longitude' => 119.8167],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Sinjai', 'latitude' => -5.1167, 'longitude' => 120.2500],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Soppeng', 'latitude' => -4.3500, 'longitude' => 119.9000],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Takalar', 'latitude' => -5.3000, 'longitude' => 119.4167],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Tana Toraja', 'latitude' => -3.1000, 'longitude' => 119.8500],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Toraja Utara', 'latitude' => -2.9667, 'longitude' => 119.9000],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kabupaten Wajo', 'latitude' => -4.1167, 'longitude' => 120.0333],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kota Makassar', 'latitude' => -5.1333, 'longitude' => 119.4167],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kota Palopo', 'latitude' => -3.0000, 'longitude' => 120.2000],
            ['provinsi' => 'Sulawesi Selatan', 'nama_wilayah' => 'Kota Parepare', 'latitude' => -4.0167, 'longitude' => 119.6167],

            // Provinsi Sulawesi Tenggara (17 wilayah)
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Bombana', 'latitude' => -4.6833, 'longitude' => 121.8333],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Buton', 'latitude' => -5.4833, 'longitude' => 122.8000],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Buton Selatan', 'latitude' => -5.5667, 'longitude' => 122.6167],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Buton Tengah', 'latitude' => -5.2833, 'longitude' => 122.7167],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Buton Utara', 'latitude' => -4.8500, 'longitude' => 123.0833],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Kolaka', 'latitude' => -4.0167, 'longitude' => 121.6000],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Kolaka Timur', 'latitude' => -4.0833, 'longitude' => 121.9333],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Kolaka Utara', 'latitude' => -3.5333, 'longitude' => 121.2333],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Konawe', 'latitude' => -3.9333, 'longitude' => 122.0667],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Konawe Kepulauan', 'latitude' => -3.9333, 'longitude' => 122.6167],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Konawe Selatan', 'latitude' => -4.2167, 'longitude' => 122.3167],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Konawe Utara', 'latitude' => -3.6667, 'longitude' => 122.0333],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Muna', 'latitude' => -4.8333, 'longitude' => 122.7167],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Muna Barat', 'latitude' => -4.8833, 'longitude' => 122.4833],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kabupaten Wakatobi', 'latitude' => -5.3167, 'longitude' => 123.5833],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kota Baubau', 'latitude' => -5.4667, 'longitude' => 122.6000],
            ['provinsi' => 'Sulawesi Tenggara', 'nama_wilayah' => 'Kota Kendari', 'latitude' => -3.9833, 'longitude' => 122.5167],

            // Provinsi Gorontalo (6 wilayah)
            ['provinsi' => 'Gorontalo', 'nama_wilayah' => 'Kabupaten Boalemo', 'latitude' => 0.5000, 'longitude' => 122.3333],
            ['provinsi' => 'Gorontalo', 'nama_wilayah' => 'Kabupaten Bone Bolango', 'latitude' => 0.5333, 'longitude' => 123.1500],
            ['provinsi' => 'Gorontalo', 'nama_wilayah' => 'Kabupaten Gorontalo', 'latitude' => 0.6000, 'longitude' => 123.0000],
            ['provinsi' => 'Gorontalo', 'nama_wilayah' => 'Kabupaten Gorontalo Utara', 'latitude' => 0.9000, 'longitude' => 122.9000],
            ['provinsi' => 'Gorontalo', 'nama_wilayah' => 'Kabupaten Pohuwato', 'latitude' => 0.8167, 'longitude' => 121.9000],
            ['provinsi' => 'Gorontalo', 'nama_wilayah' => 'Kota Gorontalo', 'latitude' => -0.5333, 'longitude' => 123.0667],

            // Provinsi Sulawesi Barat (6 wilayah)
            ['provinsi' => 'Sulawesi Barat', 'nama_wilayah' => 'Kabupaten Majene', 'latitude' => -3.5333, 'longitude' => 118.9667],
            ['provinsi' => 'Sulawesi Barat', 'nama_wilayah' => 'Kabupaten Mamasa', 'latitude' => -2.9333, 'longitude' => 119.3833],
            ['provinsi' => 'Sulawesi Barat', 'nama_wilayah' => 'Kabupaten Mamuju', 'latitude' => -2.6667, 'longitude' => 118.8833],
            ['provinsi' => 'Sulawesi Barat', 'nama_wilayah' => 'Kabupaten Mamuju Tengah', 'latitude' => -2.3167, 'longitude' => 119.3667],
            ['provinsi' => 'Sulawesi Barat', 'nama_wilayah' => 'Kabupaten Pasangkayu', 'latitude' => -1.3167, 'longitude' => 119.3667],
            ['provinsi' => 'Sulawesi Barat', 'nama_wilayah' => 'Kabupaten Polewali Mandar', 'latitude' => -3.4333, 'longitude' => 119.3333],

            // Provinsi Maluku (11 wilayah)
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Buru', 'latitude' => -3.1000, 'longitude' => 127.1000],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Buru Selatan', 'latitude' => -3.8333, 'longitude' => 126.5000],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Kepulauan Aru', 'latitude' => -5.7500, 'longitude' => 134.2167],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Kepulauan Tanimbar', 'latitude' => -7.9833, 'longitude' => 131.3000],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Maluku Barat Daya', 'latitude' => -7.7000, 'longitude' => 128.1833],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Maluku Tengah', 'latitude' => -3.3333, 'longitude' => 128.9167],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Maluku Tenggara', 'latitude' => -5.6667, 'longitude' => 132.7333],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Seram Bagian Barat', 'latitude' => -3.2500, 'longitude' => 128.1833],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kabupaten Seram Bagian Timur', 'latitude' => -3.1000, 'longitude' => 130.4667],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kota Ambon', 'latitude' => -3.7000, 'longitude' => 128.1833],
            ['provinsi' => 'Maluku', 'nama_wilayah' => 'Kota Tual', 'latitude' => -5.6333, 'longitude' => 132.7500],

            // Provinsi Maluku Utara (10 wilayah)
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kabupaten Halmahera Barat', 'latitude' => 1.0833, 'longitude' => 127.4167],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kabupaten Halmahera Tengah', 'latitude' => 0.3667, 'longitude' => 127.9833],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kabupaten Halmahera Timur', 'latitude' => 0.7000, 'longitude' => 128.3667],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kabupaten Halmahera Selatan', 'latitude' => -0.6333, 'longitude' => 127.4833],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kabupaten Halmahera Utara', 'latitude' => 1.7333, 'longitude' => 128.0167],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kabupaten Kepulauan Sula', 'latitude' => -2.1167, 'longitude' => 125.9500],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kabupaten Pulau Morotai', 'latitude' => 2.0333, 'longitude' => 128.3333],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kabupaten Pulau Taliabu', 'latitude' => -1.9333, 'longitude' => 124.8167],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kota Ternate', 'latitude' => 0.8000, 'longitude' => 127.3833],
            ['provinsi' => 'Maluku Utara', 'nama_wilayah' => 'Kota Tidore Kepulauan', 'latitude' => 0.6500, 'longitude' => 127.4333],

            // Provinsi Papua Barat (7 wilayah)
            ['provinsi' => 'Papua Barat', 'nama_wilayah' => 'Kabupaten Fakfak', 'latitude' => -2.9167, 'longitude' => 132.3000],
            ['provinsi' => 'Papua Barat', 'nama_wilayah' => 'Kabupaten Kaimana', 'latitude' => -3.6667, 'longitude' => 133.7833],
            ['provinsi' => 'Papua Barat', 'nama_wilayah' => 'Kabupaten Manokwari', 'latitude' => -0.8667, 'longitude' => 134.0500],
            ['provinsi' => 'Papua Barat', 'nama_wilayah' => 'Kabupaten Manokwari Selatan', 'latitude' => -1.4833, 'longitude' => 134.1667],
            ['provinsi' => 'Papua Barat', 'nama_wilayah' => 'Kabupaten Pegunungan Arfak', 'latitude' => -1.3500, 'longitude' => 133.9167],
            ['provinsi' => 'Papua Barat', 'nama_wilayah' => 'Kabupaten Teluk Bintuni', 'latitude' => -2.1833, 'longitude' => 133.3167],
            ['provinsi' => 'Papua Barat', 'nama_wilayah' => 'Kabupaten Teluk Wondama', 'latitude' => -2.6000, 'longitude' => 134.2500],

            // Provinsi Papua (9 wilayah)
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kabupaten Biak Numfor', 'latitude' => -1.1833, 'longitude' => 136.0833],
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kabupaten Jayapura', 'latitude' => -2.5667, 'longitude' => 140.5000],
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kabupaten Keerom', 'latitude' => -2.9167, 'longitude' => 140.7500],
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kabupaten Kepulauan Yapen', 'latitude' => -1.8833, 'longitude' => 136.2333],
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kabupaten Mamberamo Raya', 'latitude' => -2.0000, 'longitude' => 137.9500],
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kabupaten Sarmi', 'latitude' => -1.8833, 'longitude' => 138.7500],
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kabupaten Supiori', 'latitude' => -0.7333, 'longitude' => 135.5333],
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kabupaten Waropen', 'latitude' => -2.6333, 'longitude' => 136.9000],
            ['provinsi' => 'Papua', 'nama_wilayah' => 'Kota Jayapura', 'latitude' => -2.5333, 'longitude' => 140.7167],

            // Provinsi Papua Barat Daya (6 wilayah)
            ['provinsi' => 'Papua Barat Daya', 'nama_wilayah' => 'Kabupaten Maybrat', 'latitude' => -1.3333, 'longitude' => 132.5500],
            ['provinsi' => 'Papua Barat Daya', 'nama_wilayah' => 'Kabupaten Raja Ampat', 'latitude' => -0.4167, 'longitude' => 130.8167],
            ['provinsi' => 'Papua Barat Daya', 'nama_wilayah' => 'Kabupaten Sorong', 'latitude' => -0.9667, 'longitude' => 131.4000],
            ['provinsi' => 'Papua Barat Daya', 'nama_wilayah' => 'Kabupaten Sorong Selatan', 'latitude' => -1.4167, 'longitude' => 132.3000],
            ['provinsi' => 'Papua Barat Daya', 'nama_wilayah' => 'Kabupaten Tambrauw', 'latitude' => -0.9667, 'longitude' => 132.4833],
            ['provinsi' => 'Papua Barat Daya', 'nama_wilayah' => 'Kota Sorong', 'latitude' => -0.8833, 'longitude' => 131.2500],

            // Provinsi Papua Selatan (4 wilayah)
            ['provinsi' => 'Papua Selatan', 'nama_wilayah' => 'Kabupaten Asmat', 'latitude' => -5.5333, 'longitude' => 138.3833],
            ['provinsi' => 'Papua Selatan', 'nama_wilayah' => 'Kabupaten Boven Digoel', 'latitude' => -6.1000, 'longitude' => 140.3000],
            ['provinsi' => 'Papua Selatan', 'nama_wilayah' => 'Kabupaten Mappi', 'latitude' => -6.5333, 'longitude' => 139.3167],
            ['provinsi' => 'Papua Selatan', 'nama_wilayah' => 'Kabupaten Merauke', 'latitude' => -8.4833, 'longitude' => 140.3667],

            // Provinsi Papua Tengah (8 wilayah)
            ['provinsi' => 'Papua Tengah', 'nama_wilayah' => 'Kabupaten Deiyai', 'latitude' => -4.0167, 'longitude' => 136.2167],
            ['provinsi' => 'Papua Tengah', 'nama_wilayah' => 'Kabupaten Dogiyai', 'latitude' => -3.8833, 'longitude' => 136.0000],
            ['provinsi' => 'Papua Tengah', 'nama_wilayah' => 'Kabupaten Intan Jaya', 'latitude' => -3.6167, 'longitude' => 137.0500],
            ['provinsi' => 'Papua Tengah', 'nama_wilayah' => 'Kabupaten Mimika', 'latitude' => -4.5167, 'longitude' => 136.8833],
            ['provinsi' => 'Papua Tengah', 'nama_wilayah' => 'Kabupaten Nabire', 'latitude' => -3.3667, 'longitude' => 135.5000],
            ['provinsi' => 'Papua Tengah', 'nama_wilayah' => 'Kabupaten Paniai', 'latitude' => -3.9167, 'longitude' => 136.3500],
            ['provinsi' => 'Papua Tengah', 'nama_wilayah' => 'Kabupaten Puncak', 'latitude' => -3.9333, 'longitude' => 137.5000],
            ['provinsi' => 'Papua Tengah', 'nama_wilayah' => 'Kabupaten Puncak Jaya', 'latitude' => -3.5333, 'longitude' => 137.5833],

            // Provinsi Papua Pegunungan (8 wilayah)
            ['provinsi' => 'Papua Pegunungan', 'nama_wilayah' => 'Kabupaten Jayawijaya', 'latitude' => -4.1000, 'longitude' => 138.9500],
            ['provinsi' => 'Papua Pegunungan', 'nama_wilayah' => 'Kabupaten Lanny Jaya', 'latitude' => -3.8500, 'longitude' => 138.4000],
            ['provinsi' => 'Papua Pegunungan', 'nama_wilayah' => 'Kabupaten Mamberamo Tengah', 'latitude' => -3.6000, 'longitude' => 138.7500],
            ['provinsi' => 'Papua Pegunungan', 'nama_wilayah' => 'Kabupaten Nduga', 'latitude' => -4.6833, 'longitude' => 138.3167],
            ['provinsi' => 'Papua Pegunungan', 'nama_wilayah' => 'Kabupaten Pegunungan Bintang', 'latitude' => -4.9167, 'longitude' => 140.6333],
            ['provinsi' => 'Papua Pegunungan', 'nama_wilayah' => 'Kabupaten Tolikara', 'latitude' => -3.6667, 'longitude' => 138.1667],
            ['provinsi' => 'Papua Pegunungan', 'nama_wilayah' => 'Kabupaten Yahukimo', 'latitude' => -4.6667, 'longitude' => 139.7500],
            ['provinsi' => 'Papua Pegunungan', 'nama_wilayah' => 'Kabupaten Yalimo', 'latitude' => -3.6333, 'longitude' => 139.3833],
        ];

        foreach ($wilayahData as $data) {
            // Asumsi tabel 'provinsi' sudah ada dan memiliki kolom 'nama_provinsi'
            $provinsi = DB::table('provinsi')->where('nama_provinsi', $data['provinsi'])->first();

            if ($provinsi) {
                // Cek untuk menghindari duplikasi saat menjalankan seeder
                $wilayahExist = DB::table('wilayah')
                                    ->where('provinsi_id', $provinsi->provinsi_id)
                                    ->where('nama_wilayah', $data['nama_wilayah'])
                                    ->first();

                if (!$wilayahExist) {
                    DB::table('wilayah')->insert([
                        'provinsi_id' => $provinsi->provinsi_id,
                        'nama_wilayah' => $data['nama_wilayah'],
                        'latitude' => $data['latitude'],
                        'longitude' => $data['longitude'],
                    ]);
                }
            }
        }
    }
}